### ISSUE TITLE
add ability to dynamically set username/password

### ISSUE THREAD

**Issue by DennisDenuto** [concourse/bosh-deployment-resource#25]
Attempted to provide a [PR](https://github.com/concourse/bosh-deployment-resource/pull/24). however discovered it was trickier than anticipated.

It would be useful if username and password can be dynamically set (similar to how target_file works). However target_file leverages the `version` field in the output json response (which ultimately renders on concourse's gui. This won't suffice for sensitive information such as username/password)

**Comment by dsabeti** [comment]
+1

To generalize this a little bit, the bosh deployment resource sort of assumes that your bosh director is static (the exception to this is `target_file`). Allowing username and password to be dynamically discovered by concourse (and, for that matter, the deployment name) would make it easier to use a dynamically created bosh director (e.g., a bosh director set up by a previous concourse task or resource).

There might be other ways to do this. Imagine that this resource accepted a "director file" that included the director url, username, and password:

```yaml
# director_file.yml
---
url: bosh.example.com
username: admin
password: something-secret
```

Then, you could create a new "bosh director" resource that represents the state of the bosh director (as opposed to the bosh _deployment_), which produces a director file.

```yaml
# pipeline.yml
...
resources:
- name: my-bosh-deployment
  type: bosh-deployment
  source:
    deployment: deployment-name
- name: the-bosh-director
  type: bosh-director
  source:
    ... # probably something about infrastructure, like AWS creds
...

jobs:
- name: create-bosh-director
  plans:
  - put: the-bosh-director
    params:
    ... # maybe the infrastructure config goes here instead?
...
- name: do-the-bosh-deploy
  plans:
  - get: the-bosh-director
  - put: my-bosh-deployment
    params:
      director_file: the-bosh-director/director_file.yml
```



The real need here is allow for creating bosh directors in concourse builds, and then being able to use those bosh directors in subsequent builds. This is just one possible implementation I thought of. Any thoughts?
