### ISSUE TITLE
Parameters for the deployment manifest

### ISSUE THREAD

**Issue by tinygrasshopper** [concourse/bosh-deployment-resource#27]
We have a scenario in which we need to input additional fields in the deployment manifest, other than stemcell and releases, a property is dynamically generated in the pipeline which needs to be included in the manifest. 

Proposed solution:
The resource accepts a additional params `variables` with `stemcells` and `releases`

```yaml
- put: staging
  params:
    manifest: path/to/manifest.yml
    stemcells:
    - path/to/stemcells-*.tgz
    - other/path/to/stemcells-*.tgz
    releases:
    - path/to/releases-*.tgz
    - other/path/to/releases-*.tgz
    variables:
      foo: bar
      baz: quz
```

These variables can be templated in the manifest, for example in the manifest:
```yaml
instance_groups:
  - name: broker
    instances: 1
    jobs:
      - name: broker
        properties:
          port: 8080
          username: %{foo}
          password: %{baz}
``` 

Thoughts? Would accept a pull request for this behaviour?
