### ISSUE TITLE
Question: Any plans to support new BOSH CLI features like variable interpolation?

### ISSUE THREAD

**Issue by ljfranklin** [concourse/bosh-deployment-resource#35]
Just wondering if there has been any talk of supporting some of the new Golang CLI features like variable interpolation or `create-env` in this resource.

cc @vito @cppforlife @dpb587-pivotal

**Comment by vito** [comment]
Probably not `create-env`; I think that may be better off as a `bosh-env-resource` or something, since it has to persist the state file somewhere.

Supporting var interpolation sounds like a great idea. I don't know when we'd get to it, though. :/ I'll mark this as "help wanted".

Something like this?:

```yaml
put: my-deployment
params:
  var_files:
  - path/to/foo.yml
  - path/to/bar.yml
  vars:
  - name: foo
    value: bar
```
