### ISSUE TITLE
[Feature Request] Support already uploaded stemcell

### ISSUE THREAD

**Issue by shinji62** [concourse/bosh-deployment-resource#40]
Hi,

Could be nice to support already uploaded stemcells, most of the time stemcell are already in director so not need to download and them to upload them.

It could be nice if we can use it.

I was thinking about adding a new parameters like
 ```yaml
director_stemcell:
     name: bosh-warden-boshlite-ubuntu-trusty-go_agent
     version: latest
```
