### ISSUE TITLE
Support reading target address from a file

### ISSUE THREAD

**Issue by vito** [concourse/bosh-deployment-resource#6]
This would be useful for CI'ing against a pool of BOSH lite instances:

```yml
jobs:
- name: integration
  plan:
  - put: bosh-lite
    params: {acquire: true}
  - put: lite-deployment
    params: {target: bosh-lite/metadata} # assuming only metadata is the IP of the box
  - task: integration
  # ...
```
